### ISSUE TITLE
HACK.LU CTF Writeups

### ISSUE THREAD

**Issue by adulau** [ctfs/write-ups-2014#109]
https://ctftime.org/event/97/tasks/

**Comment by YASME-Tim** [comment]
These are writeups for the Hack.lu 2013 CTF. We don't have the task skeletons / a hacklu-ctf-2013 directory as far as I can see, so we need someone to add them first, before adding the writeups.

**Comment by nyx0** [comment]
Here is the repo of the ctf https://ctf.fluxfingers.net/2013/challenges

**Comment by nyx0** [comment]
@YASME-Tim I think you can close this issue I created the repo few month ago (https://github.com/ctfs/write-ups-2013/tree/master/hack-lu-ctf-2013)
