### ISSUE TITLE
Hack.lu CTF 2014: HotCows Dating

### ISSUE THREAD

**Issue by mathiasbynens** [ctfs/write-ups-2014#185]
@qll I still have a question about [the unintended solution](https://github.com/ctfs/write-ups/blob/master/hack-lu-ctf-2014/hotcows-dating/README.md#alternative-unintended-solution) for your awesome “HotCows Dating” challenge:

```
11:51:58 <mathiasbynens> fluxqll: since you wrote your thesis on it, you might be able to explain why <base href="http://ctf.opie.at:8000/"><img src="asdf works for hotcows
11:52:41 <mathiasbynens> fluxqll: i understand how <base> works but why doesn’t the CSP `img-src` set to `self` block it?
11:53:00 <mathiasbynens> fluxqll: is that a browser bug, or specced behavior?
```

**Comment by psifertex** [comment]
Can someone please clarify who came up with the alternate solution for HotCows? I need to mail them their [golden flag](http://golden-flags.com/#unexpected) trophy!

**Comment by mathiasbynens** [comment]
@psifertex The main solution was by @tomvangoethem. The alternate solution was by [team Samurai](https://wildwildweb.fluxfingers.net/2014/teams/54). I did the write-up for both, with help from @qll for figuring out why the alternate solution worked at all (Samurai didn’t really seem to know).
