### ISSUE TITLE
CSCamp CTF 2014

### ISSUE THREAD

**Issue by shankaraman** [ctfs/write-ups-2014#249]
Hey can you add CSCamp CTF writeups?

**Comment by YASME-Tim** [comment]
Please submit a pull-request with the CSCamp 2014 CTF task skeletons, since you have a better knowledge on how these tasks have been presented. Read how to [contribute](https://github.com/ctfs/write-ups-2014/blob/master/CONTRIBUTING.md) to conform to this repo's format.

**Comment by YASME-Tim** [comment]
This is a duplicate, so I'm going to close this one.
