### ISSUE TITLE
Olympic CTF 2014: Welcome to Forensics

### ISSUE THREAD

**Issue by mathiasbynens** [ctfs/write-ups-2014#28]
<http://gynvael.vexillium.org/dump/xxxx.php.txt>:

```php
<?php $_=~¾¬¬º­«; $_(~¯­¶±«.'('.~ÎÌÌÈ.')'); ?>
```

**Comment by YASME-Tim** [comment]
@mathiasbynens Is this a decrypted snippet of the WTF.BIN or a write-up in the style of the task? Or do you know what this is :smile: ?

**Comment by mathiasbynens** [comment]
No idea.
