### ISSUE TITLE
31c3 writeups

### ISSUE THREAD

**Issue by manhluat93** [ctfs/write-ups-2014#300]
Hello there :)
I wanna update my writeups on your github. My post includes:
http://l4w.io/2014/12/31c3-ctf-writeups/

pCRAPp,http, devlish, orbb,casino,cfy, mynx tasks. Ty :)

**Comment by ppepos** [comment]
Simply add the link to your writeups in the "other writeups" section of the readme.md for each challenge and open a Pull Request. 

Greatly appreciated!
Thanks =]

**Comment by YASME-Tim** [comment]
Thanks. I added the missing links to your writeups. If you could add ids for a location hash to reference the exact location of each writeup - that would be awesome ;).
