### ISSUE TITLE
Boston Key Party 2014

### ISSUE THREAD

**Issue by zachriggle** [ctfs/write-ups-2014#345]
Several writeups: https://rzhou.org/~ricky/bkpctf2014/
RARverseme writeup: https://gist.github.com/zachriggle/9302481

**Comment by zachriggle** [comment]
Some of the binaries are also hosted here:

http://repo.shell-storm.org/CTF/Boston-Key-Party-2014/
http://captf.com/2014/bostonkeyparty/

**Comment by YASME-Tim** [comment]
@zachriggle If I missed any task/writeup please submit a pull-request :). I didn't know where to put [solve2.py](https://gist.github.com/zachriggle/9302481#file-solve2-py) etc, for example. Thanks for the links!
