### ISSUE TITLE
Seccon 2014

### ISSUE THREAD

**Issue by zachriggle** [ctfs/write-ups-2014#346]
Several writeups here https://rzhou.org/~ricky/seccon2014/

**Comment by the-st0rm** [comment]
Yo Zach Riggle, you fucking spammed our inbox man

**Comment by zachriggle** [comment]
I was cloning the repo, but I cut it off at 1GB.  Too big, don't care that much.

**Comment by YASME-Tim** [comment]
@zachriggle Yeah stop using single commits for adding one link. Just add a bunch of links and then commit them once. Everybody gets an email/inbox mail for each commit+push, so that is spam. I told you last time, why don't you listen? I'm going to close your commits, redo that with ONE commit.

**Comment by mathiasbynens** [comment]
@YASME-Tim After merging a PR and before pushing it, you could also squash the commits using `git rebase`. That’s how I used to solve this problem. But you’re right that contributors should take care of it in the ideal world.

**Comment by mathiasbynens** [comment]
In @zachriggle’s defense, he was probably using the GitHub Web UI, which doesn’t allow multi-file commits or squashing/rebasing AFAIK.

@YASME-Tim After merging a PR and before pushing it, you could also squash the commits using `git rebase`. That’s how I used to solve this problem. (But you’re right that contributors should take care of this, in a perfect world.)

**Comment by YASME-Tim** [comment]
@mathiasbynens If it's only possible to do one edit/commit via GitHub Web UI, then he should at least avoid issuing 23 pull-requests for 23 commits. That at least should be possible, even with the UI. Thanks for the `git rebase` hint.

**Comment by zachriggle** [comment]
No, it's not possible with the web UI.  I don't want to clone an 800MB repo
to add a link.

**Comment by YASME-Tim** [comment]
@zachriggle Well you could fork the repo via the web UI and never would have to download it yourself. Git stores it on it's db, you edit in your links via the Web UI into your local, forked repo and in the end you just issue a pull-request. Or where lies the problem in that approach?

**Comment by zachriggle** [comment]
Ah, yep could do that in the future!  Hadn't thought of editing a forked
copy *in the browser* and then creating a PR.

I'll do that from now on.  In the meantime, would you mind merging my PRs?
It's only one more click to merge them than close them <3.

**Comment by blingblam** [comment]
seriously with this fkin spam dude.... @ZachRiggle

**Comment by zachriggle** [comment]
`s/fking spam/contributions to your project with my own free time/ig`

**Comment by YASME-Tim** [comment]
@zachriggle I've merged all pull-requests. Please [read](https://github.com/ctfs/write-ups-2015/pull/26)/care next time.
