### ISSUE TITLE
Remove year of each CTF directory name

### ISSUE THREAD

**Issue by YASME-Tim** [ctfs/write-ups-2014#353]
Since we have multiple repositories now for each year of fun CTFs: Wouldn't it be better, if we remove the redundant year of each CTF directory name and edit the [CONTRIBUTING.md](https://github.com/ctfs/write-ups-2014/blob/master/CONTRIBUTING.md) accordingly?

I don't know what to do with old CTFs (pre-2014), though. Add the year? Make a repo for each year? Make an archive repo for pre-2014 CTFs? Suggestions?

**Comment by mathiasbynens** [comment]
No, cause it would break existing links to our write-ups.

**Comment by mathiasbynens** [comment]
> I don't know what to do with old CTFs (pre-2014), though. Add the year? Make a repo for each year? Make an archive repo for pre-2014 CTFs? Suggestions?

A repo for each year seems best to me. And maybe a separate repo for evergreen CTFs/wargames (if we want to get into that).

**Comment by YASME-Tim** [comment]
Ah, right, haven't thought of existing linksreferences to write-ups of this repo. But we can use this format when adding new CTF structures for this year.

**Comment by mathiasbynens** [comment]
Better to remain consistent IMHO. It doesn’t hurt to have the extra `-2014` in the URL, IMHO. It might even help when people search for `"[ctf name] [year]"`.

**Comment by YASME-Tim** [comment]
Ok, I'll keep the year when adding new CTFs. The CTFs I've added in the last days don't have that extra year appendix, though.

**Comment by dhanvi** [comment]
guys how about going back to the past, I mean creating the year write-ups-2013 won't it make our repo more resource ??

**Comment by YASME-Tim** [comment]
@dhanvi Adding old CTFs also means spending _much_ time. This repo (2014) has already 36 CTFs. Adding solely the structure of a CTF costs about 1-2 hours, checking and collecting everything about these tasks and complying to a certain format. If you have this time, go ahead.

**Comment by dhanvi** [comment]
@YASME-Tim you just create the repo writeups 2013, and add this challenges http://shell-storm.org/repo/CTF/CSAW-2013/ I will then fork it and update it when ever I have some time to spare :+1:

**Comment by YASME-Tim** [comment]
@dhanvi I don't have the administrative power to create a new repository in ctfs. Ask @mathiasbynens :).
