### ISSUE TITLE
bata_24's writeups for numerous challenges

### ISSUE THREAD

**Issue by zachriggle** [ctfs/write-ups-2014#359]
http://pastebin.com/u/bata_24

**Comment by YASME-Tim** [comment]
Thanks @zachriggle , I've added most of them. Can't figure out which these belong to, though:

http://pastebin.com/Ls6MBuKG
http://pastebin.com/xb4tUcUp
http://pastebin.com/NS8gjEu1
http://pastebin.com/rJneD3m0

**Comment by zachriggle** [comment]
I'm not sure for those either.  Just leave those out?


*Zach Riggle*

**Comment by YASME-Tim** [comment]
Yep.
