### ISSUE TITLE
bkp14's Snapstagram binary is an old version

### ISSUE THREAD

**Issue by temporaryaccount1** [ctfs/write-ups-2014#363]
The current version at https://github.com/ctfs/write-ups-2014/tree/master/boston-key-party-2014/pwning/snapstagram is unsolvable and was replaced by another during the CTF.

**Comment by YASME-Tim** [comment]
@temporaryaccount1 Do you have the solvable version?

**Comment by YASME-Tim** [comment]
@temporaryaccount1 Is that the correct version? There are two files and I was able to find this version for snapstagram-clang.

**Comment by YASME-Tim** [comment]
This issue seems to be solved
