### ISSUE TITLE
GPN CTF Tasks

### ISSUE THREAD

**Issue by pawlos** [ctfs/write-ups-2014#87]
I've added tasks from GPN CTF 2014. Some tasks, descriptions and additional files are missing but since nobody was adding those I though I would check in what I have.

**Comment by YASME-Tim** [comment]
I've contacted the CTF organizers and all the info they could find was added [here](https://github.com/ctfs/write-ups-2014/commit/e5b93de895c6c5fd4aa605777bd4cc4e81f5668f) and [here](https://github.com/ctfs/write-ups-2014/commit/ae103ba31551841bbc7432dd1731489853bedc71)

**Comment by YASME-Tim** [comment]
I am closing this issue, since it seems to be done
